魔法使いを作成する機能の追加
yumayo14/character_game pull request #12
Opened 2019-03-29 01:55 UTC by yumayo14

## やったこと
- Wizardクラス（必要な情報を呼び出すためのインターフェイスになるクラス）
- WizardAttackCalculator、WizardDefenceCalculatorクラス（魔法使いインスタンスの攻撃力と防御力を計算するクラス）
- WizardSkillクラス（魔法使いインスタンスがどのスキルが使えるようになるかを判定する役割）
 - MaleWizardSkill、FemaleWizardSkillクラス（具体的なスキルの情報を持つ役割）

2019-03-29 05:22 UTC, yumayo14 commented
一応、反映させたいcommitのみを残すことはできたのですが、教えてもらったやり方とは違い rebase -i で戻ってコミットを消すだけでできてしまいました。
このcommitの積み方で大丈夫でしょうか

2019-03-29 07:02 UTC, kihaya commented
> 一応、反映させたいcommitのみを残すことはできたのですが、教えてもらったやり方とは違い rebase -i で戻ってコミットを消すだけでできてしまいました。
> このcommitの積み方で大丈夫でしょうか

masterから伸びた感じになってるのでよいと思います。

2019-03-29 07:04 UTC, kihaya commented
> 魔法使いを作成する機能の追加

機能といえば機能なのですが普通に「魔法使いを作成」とかでいいですよ、変に凝らずに。

2019-03-29 07:11 UTC, kihaya requested changes

2019-03-29 07:11 UTC, kihaya commented on calculators/wizard_calculators/wizard_attack_calculator.rb
> +    return 20 if equipment.name == "stick"
この処理は`stick#offence`とかを呼ぶだけよいようにできないのですかね。

2019-03-29 07:11 UTC, kihaya commented on calculators/wizard_calculators/wizard_defence_calculator.rb
> +    return 5 if element.name == "thunder"
ここも同様に`element#defence`を呼ぶだけにしたい。

2019-03-29 07:11 UTC, kihaya commented on skills/wizard_skill.rb
> +require_relative "wizard_skills/female_wizard_skill.rb"
`man` `woman` `male` `female`で揺れてるので統一してください。

2019-03-29 07:11 UTC, kihaya commented on calculators/wizard_calculators/wizard_attack_calculator.rb
> +class WizardAttackCalculator < AttackCalculator
`offence` `Attack` で揺れているので修正してください！

2019-03-29 07:11 UTC, kihaya commented on calculators/wizard_calculators/wizard_attack_calculator.rb
> +    return 20 if equipment.name == "stick"
ひょっとしたら「装備なし」というクラスが必要になるかもしれません。

2019-03-29 07:20 UTC, yumayo14 commented on calculators/wizard_calculators/wizard_attack_calculator.rb
> +    return 20 if equipment.name == "stick"
確かにそうですね。この箇所をもう少し綺麗にかける方法がないか考えてみます。

2019-03-29 07:20 UTC, yumayo14 commented on calculators/wizard_calculators/wizard_defence_calculator.rb
> +    return 5 if element.name == "thunder"
分かりました。

2019-03-29 07:20 UTC, yumayo14 commented on skills/wizard_skill.rb
> +require_relative "wizard_skills/female_wizard_skill.rb"
表記が揺れている箇所、修正します🙇‍♂️

2019-03-29 09:00 UTC, yumayo14 commented on calculators/wizard_calculators/wizard_attack_calculator.rb
> +    return 20 if equipment.name == "stick"
一度仮実装してもらったので、少しだけ見てもらってもいいでしょうか？

2019-03-29 09:12 UTC, kihaya commented on calculators/wizard_calculators/wizard_attack_calculator.rb
> +    return 20 if equipment.name == "stick"
まとめますと、装備は、攻撃力、守備力、補正値という固有の値を持って、ここでは補正値を呼び出すようにすると、「どんな装備」であっても補正をかけられるようになります。多態性ってやつですね。

2019-03-29 09:25 UTC, yumayo14 commented on calculators/wizard_calculators/wizard_attack_calculator.rb
> +    return 20 if equipment.name == "stick"
分かりました、明日作成してプルリクエストを送りたいと思います。

2019-03-29 09:30 UTC, kihaya commented on calculators/wizard_calculators/wizard_attack_calculator.rb
> +    return 20 if equipment.name == "stick"
「明日も」がんばりましょう

2019-04-02 06:54 UTC, yumayo14 commented
指摘箇所を修正したので、レビューお願いします。

2019-04-02 09:35 UTC, kihaya approved these changes

2019-04-02 09:35 UTC, merged