コメントアウトでクラスの説明文を追加
yumayo14/character_game pull request #28
Opened 2019-04-04 07:47 UTC by yumayo14

close #19 

## やったこと
- クラスを説明するコメントアウトの追加
- 変更できていなかった、引数なしprivateメソッドのインデントと行間を修正

2019-04-05 00:46 UTC, kihaya commented
そもそもこの規模のプログラムだとクラスにコメントを追加しても、名前が中身を表しているのでドキュメンテーションの意味は薄いのです。本当にコメントが必要な部分はどこかを考えてください。

2019-04-05 02:15 UTC, yumayo14 commented
分かりました、必要な箇所に絞ってコメントをするように修正します。

2019-04-05 06:01 UTC, yumayo14 commented
必要と考えられるクラスに絞って、クラスの説明を行うように変更しました。お手隙でレビューお願いします。

2019-04-05 06:55 UTC, kihaya commented
> 必要と考えられるクラスに絞って、クラスの説明を行うように変更しました。お手隙でレビューお願いします。

一番説明すべきなのは**どのような仕様で攻撃力・防御力が計算されるか**だと思うのですがいかがでしょうか。

2019-04-05 08:09 UTC, yumayo14 commented
プログラムコードだけでは `具体的にどのような処理をしているかが見えづらい`ところにこそ必要だと言うことですね。そういった場所がどこかを意識してクラスの説明を行うように変更します。

2019-04-05 08:35 UTC, kihaya commented
> そういった場所がどこかを意識してクラスの説明を行うように変更します。

「クラスそれ自体」と「クラスの継承関係と関連」が説明しているのでクラスの説明をする必要はありませんよ。

**どういう仕様で計算されるのか**が重要です。

2019-04-05 08:39 UTC, yumayo14 commented
> 「クラスそれ自体」と「クラスの継承関係と関連」が説明しているのでクラスの説明をする必要はありませんよ。

おっしゃるとおりです、、🙇‍♂️
意識して`処理を呼び出している箇所で仕様の説明`を行うようにします。

2019-04-08 09:00 UTC, kihaya requested changes

2019-04-08 09:00 UTC, kihaya commented on jobs/fighter.rb
> +  # 保有する属性（性別、属性、装備）に攻撃力が設定されていて、その合計値が返り値になる。職業との組み合わせによっては補正値がさらに追加され、追加される値はfighter_attack_calculatorに記載
長いコメントは二行で書きましょう...

2019-04-08 09:00 UTC, kihaya commented on jobs/fighter.rb
> +  # 保有する属性（性別、属性、装備）に攻撃力が設定されていて、その合計値が返り値になる。職業との組み合わせによっては補正値がさらに追加され、追加される値はfighter_attack_calculatorに記載
`記載`というのはプログラム的な表現ではないので`保持`などにするとよいかと。

2019-04-08 23:49 UTC, yumayo14 commented on jobs/fighter.rb
> +  # 保有する属性（性別、属性、装備）に攻撃力が設定されていて、その合計値が返り値になる。職業との組み合わせによっては補正値がさらに追加され、追加される値はfighter_attack_calculatorに記載
分かりました、修正します！

2019-04-09 02:57 UTC, kihaya approved these changes

2019-04-09 02:57 UTC, merged