yardを用いてクラスを説明するドキュメントファイルを作成
yumayo14/character_game pull request #34
Opened 2019-04-05 02:05 UTC by yumayo14

close #23

2019-04-05 02:16 UTC, yumayo14 commented
#28 で指摘されたように、yardの方も全てのクラスのドキュメントを作成してしまったので、必要な箇所のdocのみを作成するようにしたいと思います。

2019-04-05 08:25 UTC, kihaya commented
自動出力されるドキュメントをgit管理する必要はないと思います。Rubocop・RSpecの実行後にコード中に書かれているコメントから自動で生成されるようにすればよいと思います。

2019-04-05 08:45 UTC, yumayo14 commented
> 自動出力されるドキュメントをgit管理する必要はないと思います。Rubocop・RSpecの実行後にコード中に書かれているコメントから自動で生成されるようにすればよいと思います。

これに関して質問があるのですが、いいですか？

2019-04-10 05:37 UTC, kihaya commented on Rakefile
> +  sh 'yardoc *.rb calculators/.rb calculators/*/.rb elements/*.rb equipments/*.rb jobs/*.rb sexes/*.rb skills/*.rb'
YARDもシェル経由ではなくて、rakeタスクで呼べそうな気がしますが、そういう考えには至りませんか。
https://www.rubydoc.info/gems/yard/YARD/Rake/YardocTask
https://blog.falconsrv.net/articles/449

2019-04-10 05:59 UTC, yumayo14 commented on Rakefile
> +  sh 'yardoc *.rb calculators/.rb calculators/*/.rb elements/*.rb equipments/*.rb jobs/*.rb sexes/*.rb skills/*.rb'
おっしゃる通りですね。至っていませんでした。修正して、再度pushします🙇‍♂️

2019-04-10 06:26 UTC, yumayo14 commented on Rakefile
> +  sh 'yardoc *.rb calculators/.rb calculators/*/.rb elements/*.rb equipments/*.rb jobs/*.rb sexes/*.rb skills/*.rb'
YARDもrakeタスクで呼べる様に変更しました、お手隙でレビューお願いします。

2019-04-10 06:41 UTC, kihaya requested changes

2019-04-10 06:41 UTC, kihaya commented on Rakefile
> +task strict_test_with_docs: %i[spec yard rubocop]
インスタンス的にはどっちで書いても同じですが`%i()`の方が見かける気がしますね。
``` 
$ pry
[1] pry(main)> %i(aaa bbb)
=> [:aaa, :bbb]
[2] pry(main)> %i[aaa bbb]
=> [:aaa, :bbb]
[3] pry(main)> %i(aaa bbb) === %i[aaa bbb]
=> true
```

2019-04-10 06:41 UTC, kihaya commented on Rakefile
> +task strict_test_with_docs: %i[spec yard rubocop]
この順番だと`rubocop`が一番最後に実行されるのでテストの後では無いですが、想定した挙動ですか？
普通はビルド（テスト）に成功した、よしドキュメントを吐くぞという感じだと思いますが。

2019-04-10 07:30 UTC, tkimi commented on Rakefile
> +task strict_test_with_docs: %i[spec yard rubocop]
https://github.com/rubocop-hq/ruby-style-guide#percent-literals
ruby-style-guide 的には 配列リテラルは `[]` らしいです。 私も `()` の方が好みですが。

2019-04-10 07:51 UTC, yumayo14 commented on Rakefile
> +task strict_test_with_docs: %i[spec yard rubocop]
返信遅れてしまい申し訳ありません。
rspecのテストが通っている状態であれば、ドキュメントを生成しても問題ない状態だと考えて、rspecの後に書いていました。

2019-04-10 08:17 UTC, yumayo14 commented on Rakefile
> +task strict_test_with_docs: %i[spec yard rubocop]
が、rubocopを通ってからドキュメントを生成する様にするのがどう考えても理にかなっているので修正します。

2019-04-10 10:10 UTC, kihaya approved these changes

2019-04-10 10:10 UTC, merged