職業ごとにキャラクター一覧を作成する機能
yumayo14/character_game pull request #39
Opened 2019-04-11 03:45 UTC by yumayo14

2019-04-11 04:21 UTC, kihaya requested changes

2019-04-11 04:21 UTC, kihaya commented on guilds/fighter_guild.rb
> +class FighterGuild
`Guild`はインスタンスを作らないと全ての`character`を算出できませんよね。なので、クラスメソッドにすると良いかと思います。「クラスメソッドにするべきか、インスタンスメソッドにするべきか」問題は業務報告でお願いします！

2019-04-11 04:21 UTC, kihaya commented on guilds/fighter_guild.rb
> +    [Man.new, Woman.new].each do |sex|
ここではクラス名だけを渡す方式`[Man, Woman].each do`にして、Fighterの初期化でついでに初期化する方式にするとわかりやすいかと思います。

2019-04-11 04:21 UTC, kihaya commented on guilds/fighter_guild.rb
> +          member << Fighter.new(sex: sex, element: element, equipment: equipment)
ここの生成処理はほぼ共通なので`Guild`によって生成処理を切り替える感じにしてほしいですね。

2019-04-11 04:21 UTC, kihaya commented on spec/guilds/fighter_guild_spec.rb
> +      describe '1人目' do
ここなんか分け過ぎじゃないですか？`一人目の職業は武闘家`とかよいのでは。

2019-04-11 04:26 UTC, yumayo14 commented on guilds/fighter_guild.rb
> +class FighterGuild
分かりました、調べて業務報告の方で報告させていただきます！

2019-04-11 04:26 UTC, yumayo14 commented on guilds/fighter_guild.rb
> +    [Man.new, Woman.new].each do |sex|
確かに、、
ありがとうございます。Fighterの初期化時に他のものも初期化する様に書き換えたいと思います。

2019-04-11 04:30 UTC, kihaya commented on guilds/fighter_guild.rb
> +class FighterGuild
調べずに自分がどう思うかを教えてください。

2019-04-11 04:34 UTC, kihaya commented
PRの説明がありませんね、pryでの実行結果などは貼らないのですか？

2019-04-11 05:03 UTC, yumayo14 commented on guilds/fighter_guild.rb
> +class FighterGuild
分かりました

2019-04-12 09:48 UTC, kihaya approved these changes

2019-04-12 09:48 UTC, kihaya commented on character_factory.rb
> +class CharacterFactory
よい設計だと思います。`Factory`パラーンのよい使い方です👍

2019-04-12 09:48 UTC, merged