キャラの強さを判定するクラスを作成
yumayo14/character_game pull request #40
Opened 2019-04-11 03:49 UTC by yumayo14

2019-04-11 04:31 UTC, kihaya requested changes

2019-04-11 04:31 UTC, kihaya commented on power_checker.rb
> +    members.map { |character| character.attack + character.defence }.max
もしや
攻撃力100、防御力0
攻撃力50、防御力50
のキャラクターが同列ですか...？

2019-04-11 04:34 UTC, kihaya commented
PRの説明がありませんね、pryでの実行結果などは貼らないのですか？

2019-04-11 04:36 UTC, yumayo14 commented on power_checker.rb
> +    members.map { |character| character.attack + character.defence }.max
はい、、そうなります、、、、

2019-04-11 04:55 UTC, yumayo14 commented
申し訳ありません、PRメッセージとコードで十分と考えて載せていませんでした。
確かに、pryでの実行結果などがないとどういうデータが返ってきているのかが分からないですね。
必要そうな箇所は、適宜載せる様にしたいと思います。

2019-04-12 10:14 UTC, kihaya commented
このブランチは`Guild`クラスが含まれていますが、masterから生やしましたか？

2019-04-12 11:28 UTC, yumayo14 commented
![スクリーンショット 2019-04-12 20 27 28](https://user-images.githubusercontent.com/31206922/56034151-7a810f00-5d61-11e9-949e-cd154c94e908.png)

この箇所のことですか？

2019-04-15 00:32 UTC, kihaya commented
プログラムの出力結果が見づらいので整形してください

2019-04-15 02:06 UTC, yumayo14 commented
分かりました、整形します。

2019-04-15 03:22 UTC, kihaya commented
> 分かりました、整形します。

特に今回つくっているプログラムは単体で実行可能ではないので、
pry上でこういう入力をしたらこういう出力が返る、というのを以下のように示してほしいです。
```
 $ pry
[1] pry(main)> 1 + 1
=> 2
```

2019-04-15 07:59 UTC, kihaya commented
`binding.pry`で止めてクラスの動作確認をしなくてもpryからファイルをロードしてテストをすれば良いと思うのです。

2019-04-15 08:03 UTC, kihaya commented on spec/character_checker_spec.rb
> +      expect(character_checker.best_characters.first.class.name).to eq 'Warrior'
ここだけなんで`class`の判定ではないのでしょう。

2019-04-15 08:09 UTC, yumayo14 commented
> binding.pryで止めてクラスの動作確認をしなくてもpryからファイルをロードしてテストをすれば良いと思うのです。

おっしゃる通りでした、修正します🙇‍♂️

2019-04-15 08:14 UTC, yumayo14 commented on spec/character_checker_spec.rb
> +      expect(character_checker.best_characters.first.class.name).to eq 'Warrior'
eq マッチャーで比較するときは、文字列か数値でないといけないと思い込んでいました。
classオブジェクトでも比較できたので修正します。

2019-04-16 05:25 UTC, kihaya requested changes

2019-04-16 05:25 UTC, kihaya commented on spec/character_checker_spec.rb
> +      expect(character_checker.best_characters.count).to eq 2
ここもsubjectにしたほうがいいですね。

2019-04-16 07:01 UTC, yumayo14 commented
こちらも書き直せたので、お手隙でお願いします。

2019-04-16 07:40 UTC, kihaya commented
rebaseして向き先を`master`にしていただけると。

2019-04-16 08:43 UTC, yumayo14 commented
PRの向きを変更しました、よろしくお願いします🙇‍♂️

2019-04-16 09:08 UTC, kihaya approved these changes

2019-04-16 09:08 UTC, merged