各職業のキャラ一覧作成をとキャラの強さを判定を呼び出すクラスを作成
yumayo14/character_game pull request #41
Opened 2019-04-11 03:50 UTC by yumayo14

2019-04-11 04:24 UTC, kihaya requested changes

2019-04-11 04:24 UTC, kihaya commented on spec/guild_spec.rb
> +  describe '#initialize' do
発想的には確かにコンストラクタのテストなんですけど、ここの`initialize`はなくてよいですよ。

2019-04-11 04:24 UTC, kihaya commented on guild.rb
> +class Guild
`Guild`という名前だといかにも`FighterGuild`の親クラスっぽい名前なので違う名前にしてあげてください。

2019-04-11 04:34 UTC, kihaya commented
PRの説明がありませんね、pryでの実行結果などは貼らないのですか？

2019-04-11 04:58 UTC, yumayo14 commented on spec/guild_spec.rb
> +  describe '#initialize' do
分かりました、`#initialize`のレイヤーを消して、テストを書き直そうと思います。

2019-04-11 05:02 UTC, yumayo14 commented on guild.rb
> +class Guild
分かりました。継承していない場合は紛らわしい名前をつけない様にしたいと思います。

2019-04-15 08:01 UTC, kihaya commented on guild.rb
> +class Guild
ここは修正しないということでよいですか・

2019-04-16 00:16 UTC, yumayo14 commented on guild.rb
> +class Guild
`FighterGuildクラス` `WarriorGuildクラス` `WizardGuildクラス`という似た名前のクラスが無くなったので、`Guildクラス`の名前は変えなくても大丈夫だと思い、変えていませんでした。

2019-04-16 00:17 UTC, yumayo14 commented on guild.rb
> +class Guild
`Guildクラス` の名前は変えないで進めていこうと考えています。

2019-04-16 00:27 UTC, kihaya commented
マージコミットがブランチに含まれてしまっていますよ

2019-04-16 00:33 UTC, yumayo14 commented
変更差分を出さない様に、このブランチに向けて出していたPRがそのままmergeされてしまったみたいです。一度、mergeコミットを打ち消して、再度merge先の説明文を記載したPRを作りなおす形で大丈夫でしょうか？

2019-04-16 00:36 UTC, kihaya commented
> 変更差分を出さない様に、このブランチに向けて出していたPRがそのままmergeされてしまったみたいです。一度、mergeコミットを打ち消して、再度merge先の説明文を記載したPRを作りなおす形で大丈夫でしょうか？

基本的には打ち消さずに、最新の`master`から生やし直して、このブランチの変更コミットを`cherry-pick`し、`force push`すればよいと思います。

2019-04-16 00:41 UTC, yumayo14 commented
分かりました、このブランチの変更コミットのみを積んだ、同名のブランチを `force-push` したいと思います。
その後、masterから新しいブランチをきり、`rubocop.ymlを変更するためのPR`を別に出したいと思います。

2019-04-16 05:15 UTC, kihaya approved these changes

2019-04-16 05:15 UTC, merged