キャラクターの強さ判定機能を呼び出si
yumayo14/character_game pull request #43
Opened 2019-04-15 07:27 UTC by yumayo14

2019-04-15 08:06 UTC, kihaya commented
`master`以外のブランチに向ける場合にはPRの説明にそのように書くとよいです。

2019-04-15 08:32 UTC, kihaya commented
> `master`以外のブランチに向ける場合にはPRの説明にそのように書くとよいです。

主に2パターンあります。
+ `master`・開発ブランチに対してマージしたい場合
+ 集約ブランチに対してマージしたい場合

master・開発ブランチに対してマージしたい場合には、差分を出さないようにするために向けている**前提となるブランチに**うっかりマージしてしまったりするので要注意です。

2019-04-15 08:48 UTC, yumayo14 commented
ご丁寧にありがとうございます。
今後は、 **何故、master以外に向けているのか ** と ** どの様にマージしてほしいか ** をPRの説明に書くようにしたいと思います。

2019-04-16 05:24 UTC, kihaya requested changes

2019-04-16 05:24 UTC, kihaya commented on spec/guild_spec.rb
> +      expect(guild.best_attackers.first.class.name).to eq 'Warrior'
ここはクラス名での判定にしないのですか？

2019-04-16 05:24 UTC, kihaya commented on spec/guild_spec.rb
> +      expect(guild.best_characters.count).to eq 2
メソッド単位で切れているので、subjectにしたらどうでしょうか。

2019-04-16 05:58 UTC, kihaya commented on spec/guild_spec.rb
> +      expect(guild.best_attackers.first.class.name).to eq 'Warrior'
`be_instance_of`マッチャなどを使うとうまく切れそうです。
https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/type-matchers

2019-04-16 07:00 UTC, yumayo14 commented
subject {  } を使ってテストケースを書き直しました。お手隙でレビュー、お願いします。

2019-04-16 07:37 UTC, kihaya approved these changes
![DswEw0rUcAAhVRY](https://user-images.githubusercontent.com/7752434/56190773-efa45b00-6065-11e9-85f2-a670195aa7ba.jpg)

2019-04-17 00:14 UTC, merged